### ISSUE TITLE
Swift/UnsafeBufferPointer.swift:898: Fatal error

### ISSUE THREAD

**Issue by ryanisnhp** [konrad1977/loco#1]
Hi bro I just clone and use this one and it crash with this error, can you help me to check this
<img width="590" alt="Screen Shot 2022-07-27 at 17 54 29" src="https://user-images.githubusercontent.com/26299033/181230537-f875b664-af71-4a57-857b-e7d1235e66ac.png">

**Comment by konrad1977** [comment]
I´ve seen the error while developing but I can not reproduce (nor on X86 or Apple Silicon). 
Is this a public repo? Can you reproduce it everytime?

**Comment by ryanisnhp** [comment]
No, it's a private project so I cannot share, but I try on 3 different laptops ( all of them is chip M1) but not work

**Comment by konrad1977** [comment]
Coud you try adding the path to the scheme (Edit Scheme | Options -> Working Directory] in Xcode and see if you get more info from the LLDB when running the program directoy from within Xcode.

I am running Loco on my M1 Pro with M1 Pro chip just fine. Ill do a few more checks, but I will be away for a week or two right now. If you find the bug please do a Pull Request.

**Comment by aokj4ck** [comment]
I'm seeing the same issue on an M1 Mac. 

Steps to reproduce:

```
git clone git@github.com:konrad1977/loco.git
swift build
# At this time .build/debug is an alias directory to .build/arm64-apple-macosx/debug/
```

```
# When I invoke the executable in an Xcode project directory it using the full path
# /Users/jack/dev/loco/.build/arm64-apple-macosx/debug/loco
Swift/UnsafeBufferPointer.swift:898: Fatal error
[1]    50049 trace trap  /Users/jack/dev/loco/.build/arm64-apple-macosx/debug/loco
```

**Comment by konrad1977** [comment]
I updated the repo today, could you please check if you can reproduce it again?

**Comment by aokj4ck** [comment]
Yes that worked for me building from Terminal. Thank you!

What are the steps to build a flat file binary for regular usage? If I move `.build/arm64-apple-macosx/debug/loco` will it have everything it needs to execute? I can try moving it and open new issue.

**Comment by konrad1977** [comment]
```
cd /loco
swift build -c release
```
This should produce a release binary. Put it in `/usr/local/bin` and you are ready to go

**Comment by ryanisnhp** [comment]
just checked, it works on my side also

**Comment by konrad1977** [comment]
I am closing this bug then. Happy linting and thanks for reporting the bug!
