### ISSUE TITLE
Keys are being used by still show that keys are unused

### ISSUE THREAD

**Issue by ryanisnhp** [konrad1977/loco#3]
I run `loco` on my project it shows that the key `no_data_empty` is unused but I search again in project and that key are being used. Do I use your localization format correctly or this is a bug?

<img width="943" alt="image" src="https://user-images.githubusercontent.com/26299033/183817086-d03c75d4-a302-45f8-ac71-59f809846918.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/26299033/183817029-e21173be-ba21-4b1f-9859-8094e6e08e82.png">

**Comment by konrad1977** [comment]
It doesn't understand your extension on String. Change to NSLocalizedString or String(localization: ) and it should work just fine.

**Comment by konrad1977** [comment]
I have a plan for this. Check back in a few days/week or two

**Comment by konrad1977** [comment]
@ryanisnhp I  just updated. Could you try again with the latest version?

**Comment by ryanisnhp** [comment]
I checked again on the latest version and it's ok @konrad1977
