### ISSUE TITLE
Custom Localised Strings pattern

### ISSUE THREAD

**Issue by romaHerman** [konrad1977/loco#5]
Hi @konrad1977  
Creating a separate issue

I did update to the latest version. It doesn't coght all the strings for me. 
I was able to fix this by altering the  `RegexPattern` file like this: 

```
   static var sourceRegex: String {
        buildSourceRegex(
          [
            "\\.navigationTitle",
            "Label",
            "DatePicker",
            "Text",
            "Picker",
            "Button",
            "Toggle",
            "LocalizedStringKey",
            "NSLocalizedString",
            "String\\(localized:",
            "MyLocalizedString\\(",
          ]
        )
    }
```

also, I was trying to add a reg exps but failed for now for such cases: 
let arrayOfLocalizedKeys = ["key_1", "key_2"];
let key = resourceAvailable ? "key_1" : "key_2"; 
enum States: String {
case online = "online_key"
case offline = "ofline_key"
}

or maybe there is a way to suppress individual strings.

**Comment by konrad1977** [comment]
Could you paste a bit of your code. You can mask variable and function names. Just show me something that doesn't get caught.

**Comment by romaHerman** [comment]
this doesn't get caught 
```
let subtitleKey = info.hasItem ? "absence.edit_details_instructions" : "absence.details_instructions"
let action_title = status ? MyLocalizedString("messenger.revoke_access") : MyLocalizedString("messenger.promote")
let key = pinned ? "news_pin_success" : "news_unpin_success"
```
i wonder now that maybe it's the dot in the key name

also system permissions 
but that's a minor one 
```
"NSCalendarsUsageDescription" = "This app need to access your calendar";
```

also, I have some keys which I'd like to suppress but that's also a minor thing. They arrive from the server as a key.

**Comment by konrad1977** [comment]
Thanks I'll look into it.

**Comment by romaHerman** [comment]
Thanks a lot

**Comment by konrad1977** [comment]
There is a temporary fix up now. This will include commented out and empty strings. Its not performant but should work for you.

**Comment by romaHerman** [comment]
Thanks a lot! 
It works now
